"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['GSI.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS,
             'iconfile':'/Users/gregstewart96/Documents/LaTex/Images/Alba.gif'},
    setup_requires=['py2app'],
)
